#!/usr/bin/env python
"""Project 2 Grading Script

Usage:
    ./proj2.py <dir> <files>...
"""

from utilities import *

submission_filters = {
    "required": ["SimFishy.cpp",
                 "Fish.h", "Fish.cpp",
                 "FishTank.h", "FishTank.cpp"]
    , "permitted": []
}

if __name__ == "__main__":
    from docopt import docopt
    arguments = docopt(__doc__, version="Tufts Comp11 Project2 v2014s")

    screenUname(".el6")
    screenGxx((4, 8, 0))  # this means g++ >= 4.8.0
    screenFilenames(arguments["<files>"], submission_filters)
    print "Compiling your code ..."
    (code0, _, err0) = build(["SimFishy.cpp", "Fish.cpp", "FishTank.cpp"], "SimFishy")

    if code0:
        print "Here are the errors generated by the compiler:"
        print err0
        print "Your code did not build!"
    print "There are no runtime tests for this project."
